[versions]
agp = "7.2.2"
android-junit5 = "1.8.2.1"
androidx-appcompat = "1.4.2"
androidx-core = "1.8.0"
coroutines = "1.6.4"
detekt = "1.21.0"
junit = "5.8.2"
kotlin = "1.7.10"
material = "1.6.1"
truth = "1.1.3"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
material = { module = "com.google.android.material:material", version.ref = "material" }

test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
test-junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
test-junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
test-junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
test-truth = { module = "com.google.truth:truth", version.ref = "truth" }

[bundles]
unitTest = ["test-junit-api", "test-junit-params", "test-truth", "test-coroutines"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "android-junit5" }
android-library = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
