[versions]
agp = "7.3.1"
android-junit5 = "1.8.2.1"
androidx-appcompat = "1.5.1"
androidx-core = "1.9.0"
androidx-junit = "1.1.3"
compose= "1.3.0"
compose-material3 = "1.1.0-alpha01"
coroutines = "1.6.4"
dagger = "2.44"
detekt = "1.21.0"
espresso = "3.4.0"
fragment = "1.5.4"
junit4 = "4.13.2"
junit = "5.9.1"
lifecycle = "2.5.1"
kotlin = "1.7.10"
ksp = "1.7.10-1.0.6"
material = "1.8.0-alpha02"
room = "2.4.3"
truth = "1.1.3"
turbine = "0.9.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose"}
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose"}
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
material = { module = "com.google.android.material:material", version.ref = "material" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

test-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
test-junit4 = { module = "junit:junit", version.ref = "junit4" }
test-junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
test-junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
test-junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
test-truth = { module = "com.google.truth:truth", version.ref = "truth" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

# :build-logic
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
unitTest = ["test-junit-api", "test-junit-params", "test-truth", "test-coroutines", "test-turbine"]
room = ["room-ktx", "room-runtime"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "android-junit5" }
android-library = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

